In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("DataCovid.csv")

In [9]:
df

    Person Covid  Flu Fever
0        1   Yes   No   Yes
1        2    No  Yes   Yes
2        3   Yes  Yes   Yes
3        4    No   No    No
4        5   Yes   No   Yes
5        6    No   No   Yes
6        7   Yes   No   Yes
7        8   Yes   No    No
8        9    No  Yes   Yes
9       10    No  Yes    No
10      11   Yes  Yes   NaN

In [7]:
newDF = df.drop(df.columns[0], axis = 1)
mat = newDF.to_numpy()
print(mat)

[['Yes' 'No' 'Yes']
 ['No' 'Yes' 'Yes']
 ['Yes' 'Yes' 'Yes']
 ['No' 'No' 'No']
 ['Yes' 'No' 'Yes']
 ['No' 'No' 'Yes']
 ['Yes' 'No' 'Yes']
 ['Yes' 'No' 'No']
 ['No' 'Yes' 'Yes']
 ['No' 'Yes' 'No']
 ['Yes' 'Yes' nan]]

In [11]:
row = mat.shape[0]-1 ## This R does not consist of the last row to be predicted
col = mat.shape[1]

In [12]:
countYes=0
for i in range(row):
    if mat[i][col-1] == "Yes":
        countYes+=1
countNo=row-countYes
P = countYes/row ## P for P(E=Yes)
NP = countNo/row ## NP for P(E=No)

In [15]:
Pyes=1
Pno=1
for c in range(col-1):
    instanceVal=mat[row][c]
    countInstanceYes=0
    countInstanceNo=0
    for r in range(row):
        if mat[r][c]==instanceVal:
            if mat[r][col-1]=="Yes":
                countInstanceYes+=1
            else:
                countInstanceNo+=1
    Pyes=Pyes*(countInstanceYes/countYes)
    Pno=Pno*(countInstanceNo/countNo)
Pyes=Pyes*P
Pno=Pno*NP
print(f"Yes = {Pyes}")
print(f"No = {Pno}")

Yes = 0.1714285714285714
No = 0.03333333333333333

In [16]:
if Pyes>Pno:
    df.iloc[row, col] = "Yes"
else:
    df.iloc[row, col] = "No"

In [17]:
df.tail()

    Person Covid  Flu Fever
6        7   Yes   No   Yes
7        8   Yes   No    No
8        9    No  Yes   Yes
9       10    No  Yes    No
10      11   Yes  Yes   Yes

In [18]:
df.to_csv("Prediction.csv", index=False)

In [19]:
predictionDF=pd.read_csv("Prediction.csv")
predictionDF

    Person Covid  Flu Fever
0        1   Yes   No   Yes
1        2    No  Yes   Yes
2        3   Yes  Yes   Yes
3        4    No   No    No
4        5   Yes   No   Yes
5        6    No   No   Yes
6        7   Yes   No   Yes
7        8   Yes   No    No
8        9    No  Yes   Yes
9       10    No  Yes    No
10      11   Yes  Yes   Yes